ARG NODE_VERSION=lts-slim
FROM node:${NODE_VERSION}

ENV NODE_ENV=production
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY server ./server

EXPOSE 3000

CMD ["node", "server/index.js"]
